from pathlib import Path
from datetime import datetime

REPORT_PATH = Path("reports/security-report.md")

def main():
    report = f"""# Security Pipeline Report

Generated At: {datetime.utcnow().isoformat()}Z

## Summary

This is a demo report generated by the DevSecOps Pipeline Starter Kit.

## Checks

| Check | Status |
|---|---|
| Secret Scan | Passed |
| Dependency Scan | Review Required |
| Container Scan | Review Required |
| SAST | Review Required |

## Recommendation

Review high and critical findings before release.
"""

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report)

# //TODO make this parse Trivy/Semgrep/Gitleaks JSON properly

if __name__ == "__main__":
    main()